### ISSUE TITLE
Create distances object

### ISSUE THREAD

**Issue by guivivi** [fsavje/Rscclust#10]
Hello,

I have a similarity matrix `df0` such as 
`object1 object2 similarity`
`x1       y1        0.09`
`x2       y2        0.25`

I can create the a `dist` object with 
`nams <- with(df0, unique(c(as.character(object1), as.character(object2))))`
`df1 <- with(df0, structure(similarity, Size = length(nams), Labels = nams, Diag = FALSE, Upper = FALSE, method = "user", class = "dist"))`

Then, I can use for example kmeans with this `dist` matrix. However, in order to use `sc_clustering` from `scclust`, I need a `distances` object. Do you know how I can create it, either directly from the similarity matrix, or from the `dist` object?

Thanks in advance.

**Comment by fsavje** [comment]
To create a `distances` object, you need to feed the constructor function the vector space in which to derive distances. In particular, the `distances` object does not support arbitrary metric spaces; it focuses on Euclidean distances. In your case, you need to create the `distances` object using the data points that were used to create `df0` in your example.

On a side note, if you are using R's `kmeans` function with the matrix `df1` as constructed in your example, you are not getting a kmeans clustering based on the data points. Instead, you are clustering the distance matrix itself. You can see this by inspecting the dimension of the centroids.  I suspect that is not what you want. Also for `kmeans`, you need to feed in the raw data points.

**Comment by guivivi** [comment]
I see, many thanks for the insights. You're right, I meant for example `pam`, that does accept dissimilarities.
