### ISSUE TITLE
Error in check_clustering(clustering = my_clustering): size_constraint must be scalar. 

### ISSUE THREAD

**Issue by MatthieuStigler** [fsavje/Rscclust#13]
Hi

I am just trying to rerun the example, and get a warning: 

> Error in check_clustering(clustering = my_clustering): `size_constraint` must be scalar.

Thanks!

``` r
library(scclust)
#> Loading required package: distances

my_data <- data.frame(id = 1:100000,
                      type = factor(rbinom(100000, 3, 0.3),
                                    labels = c("A", "B", "C", "D")),
                      x1 = rnorm(100000),
                      x2 = rnorm(100000),
                      x3 = rnorm(100000))

# Construct distance metric
my_dist <- distances(my_data,
                     id_variable = "id",
                     dist_variables = c("x1", "x2", "x3"))

# Make clustering with at least 3 data points in each cluster
my_clustering <- sc_clustering(my_dist, 3)
check_clustering(my_clustering)
#> Error in check_clustering(clustering = my_clustering): `size_constraint` must be scalar.
```

<sup>Created on 2023-05-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by fsavje** [comment]
Hi @MatthieuStigler 

Thanks for the report! The purpose of the `check_clustering()` function is to check whether the provided clustering satisfies some size and/or type restrictions. Hence, the function must be called with at least one of `size_constraint` and `type_constraints`. In the example in the documentation, the call is `check_clustering(my_clustering, 3)`. However, in your snippet, you have `check_clustering(my_clustering)`. I.e., you ask to check the clustering for size and/or type restrictions, but do not provide what the restrictions are. If you simply want to check whether `my_clustering` is a clustering object, please use  `is.scclust(my_clustering)`.

Best,
Fredrik

**Comment by MatthieuStigler** [comment]
oh, my bad, I went through too quickly, sorry about that! :-(
