### ISSUE TITLE
Possible to set a maximum limit on cluster size?

### ISSUE THREAD

**Issue by benmarwick** [fsavje/Rscclust#5]
I can't seem to see this implemented here or in any R pkg for clustering. Do you think it's possible?

**Comment by cf814** [comment]
I am having this issue as well and sadly see no one has responded. Maybe it would be possible by adjusting the method or algorithm.

**Comment by fsavje** [comment]
@benmarwick @cf814 Please excuse the slow response.

Restrictions on the maximum cluster size can be imposed in some settings. But it is not possible to encode such restrictions directly in the graph the algorithm uses, so one has to be a bit creative.

One approach is to impose the minimum and maximum size constraints separately. I.e., first use the `sc_clustering()` function to construct clusters that obey the minimum constraint. Then, in a second step, split clusters that are too large into smaller clusters. The function `hierarchical_clustering()` can be used for the second step. This will work whenever the maximum size constraint is at least twice the minimum size, and the clustering has the same optimality properties as when only minimum constraints are used.

Another option is to call `sc_clustering()` with `primary_unassigned_method = "ignore"`. This will construct clusters that are exactly of the minimum size. However, some data points may not be assigned to clusters in that case. The unassigned points can be assigned to clusters as a post-processing step (while checking the maximum size constraint). This is not implemented in the package, but should be fairly straight forward to do by using, e.g., the `nearest_neighbor_search()` function in the [`distances`](https://github.com/fsavje/distances) package. This approach works for any maximum cluster size, but the optimality properties do not apply.

Clustering problems without minimum size constraints (or constraints on the number of the clusters) have a trivial optimal solution: just make one cluster for each data point.

I hope this will be helpful to solve the problems. Please let me know if not.

**Comment by guivivi** [comment]
Hello,

Would it be possible to add this extension in the scclust R package for the maximum size constraint? 
https://github.com/Behrouz-Babaki/MinSizeKmeans#extension 

Thanks in advance.

**Comment by fsavje** [comment]
Thanks for asking. No, the approach you link to cannot be implemented here. The algorithm by Bradley et al. (2000) is based on network flow, which is very different for the algorithm used by scclust.

**Comment by guivivi** [comment]
Ok, many thanks for the reply.
