### ISSUE TITLE
error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode

### ISSUE THREAD

**Issue by slowkow** [fsavje/Rscclust#7]
I'm just trying to install the package after cloning it from github:

```
R CMD INSTALL .
```

I tried explicitly setting `-std=c99` like this:

```
# ~/.R/Makevars
CC=gcc -std=c99
```

Still, I got:

```
src/digraph_core.c: In function ‘iscc_digraph_is_valid’:
src/digraph_core.c:62:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for (size_t i = 0; i < dg->vertices; ++i) {
  ^
src/digraph_core.c:62:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
```

The problem is in `src/libscclust/Makefile`:

https://github.com/fsavje/scclust-R/blob/796f4593c286c7f71355125ac3f956e9f0d1a678/src/libscclust/Makefile#L33-L34

I changed it to be this:

```
%.o: %.c
 	$(CC) -std=c99 -c $(ALL_CPPFLAGS) $(ALL_CFLAGS) $(XTRA_FLAGS) $< -o $@
```

And then the build worked without errors.

So, the `Makefile` needs to be modified so it can "see" the configuration variables inside `~/.R/Makevars`.

Unfortunately, I can't find any good documentation for how to do this the right way...

The [R-exts] documentation is difficult to read, but maybe it has the answer.

[R-exts]: https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html

**Comment by fsavje** [comment]
Thank you @slowkow for the bug report. I'll take a look during the weekend. In the meanwhile, could you copy-paste your session info (i.e., just run `sessionInfo()` in R).

Also, which compiler are you using?

**Comment by slowkow** [comment]
```
gcc --version
gcc (GCC) 4.9.2
```

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.5 (Santiago)

Matrix products: default
BLAS: /apps/lib-osver/R/3.4.0/lib64/R/lib/libRblas.so
LAPACK: /apps/lib-osver/R/3.4.0/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] colorout_1.1-2

loaded via a namespace (and not attached):
[1] compiler_3.4.0
```

**Comment by fsavje** [comment]
Thanks!

I find this weird. Portable code according the R extension manual is C99 code, so your compiler should be called to accept for loop declarations. I haven't seen that R's C compiler have defaulted to some strict version of ANSI C. It's almost that your installation of R is misconfigured (I suspect you would have the same bug with a lot of CRAN packages).

However, it doesn't hurt to specify that the library is C99, and I've added the flag to the Makefile. When you get a chance, please give the development version a try and let me know how it works.

**Comment by slowkow** [comment]
Fredrik, thank you for looking into this! I appreciate it.

As far as I can recall, I haven't encountered this particular bug (about for loop declarations) with any other package. I'm not certain.

Sorry for bothering you about this. It is probably an issue with my environment, and I'm not sure if you should make any changes to your `Makefile` or not. Thanks again for having a look!

In the comments below, I try to shed some light on why this error happened on my system.

---

At some point during the build, this command is executed:

```bash
(cd libscclust && MAKECONF="/apps/lib-osver/R/3.4.0/lib64/R/etc/Makeconf" make) || exit 1;
```

Since the `CC` variable and other variables are taken from that `Makeconf` file, they override what I have in my `~/.R/Makevars`.

Looking at the build error again, I can see that `-std=XXX` is passed 4 times to the first `gcc` command:

- `-std=c11`
- `-std=c99`
- `-std=c11`
- `-std=`

That does not seem right to me... I don't know why that happens, but it seems to work OK anyway.

After the `cd libscclust && MAKECONF=...` command, the next 2 `gcc` commands have no `-std=XXX` option at all. That's why I get the build error -- the build completes successfully when I put `-std=c99` directly into `src/libscclust/Makefile`.

<details>
<summary>Build commands</summary>

<pre>
gcc -I/apps/lib-osver/R/3.4.0/lib64/R/include -DNDEBUG -Ilibscclust/include  -I/apps/lib-osver/gcc/6.3.0//include -L/apps/lib-osver/gcc/6.3.0/lib64 -L/apps/lib-osver/gcc/6.3.0/lib6:-I/source/z
lib/1.2.8/include: -I/source/zlib/1.2.8/include -L/source/zlib/1.2.8/lib -I/source/bzip2/1.0.6/include -L/source/bzip2/1.0.6/lib -I/source/lzma/5.0.7/include -L/source/lzma/5.0.7/lib -I//apps/
lib-osver/pcre/8.38/include -L/apps/lib-osver/pcre/8.38/lib -I/source/libcurl/7.35.0/include -I/source/libcurl/7.35.0/lib  -std=c11 -I/PHShome/ks38/.local/include -L/PHShome/ks38/.local/lib  -
std=c99 -I/PHShome/ks38/.local/include -L/PHShome/ks38/.local/lib -std=c11 -I/PHShome/ks38/.local/include -L/PHShome/ks38/.local/lib -fpic  -I/apps/lib-osver/gcc/6.3.0//include -L/apps/lib-osv
er/gcc/6.3.0/lib64 -L/apps/lib-osver/gcc/6.3.0/lib6:-I/source/zlib/1.2.8/include: -I/source/zlib/1.2.8/include -L/source/zlib/1.2.8/lib -I/source/bzip2/1.0.6/include -L/source/bzip2/1.0.6/lib
-I/source/lzma/5.0.7/include -L/source/lzma/5.0.7/lib -I//apps/lib-osver/pcre/8.38/include -L/apps/lib-osver/pcre/8.38/lib -I/source/libcurl/7.35.0/include -I/source/libcurl/7.35.0/lib   -std=
c11 -I/PHShome/ks38/.local/include -L/PHShome/ks38/.local/lib -c utilities.c -o utilities.o

(cd libscclust && MAKECONF="/apps/lib-osver/R/3.4.0/lib64/R/etc/Makeconf" make) || exit 1;

make[1]: Entering directory `/tmp/RtmpsrwRMk/R.INSTALL21e47c3f3c6e/scclust/src/libscclust'

gcc -c -I/apps/lib-osver/R/3.4.0/lib64/R/include -DNDEBUG   -I/apps/lib-osver/gcc/6.3.0//include -L/apps/lib-osver/gcc/6.3.0/lib64 -L/apps/lib-osver/gcc/6.3.0/lib6:-I/source/zlib/1.2.8/include
: -I/source/zlib/1.2.8/include -L/source/zlib/1.2.8/lib -I/source/bzip2/1.0.6/include -L/source/bzip2/1.0.6/lib -I/source/lzma/5.0.7/include -L/source/lzma/5.0.7/lib -I//apps/lib-osver/pcre/8.
38/include -L/apps/lib-osver/pcre/8.38/lib -I/source/libcurl/7.35.0/include -I/source/libcurl/7.35.0/lib    -fpic  -I/apps/lib-osver/gcc/6.3.0//include -L/apps/lib-osver/gcc/6.3.0/lib64 -L/app
s/lib-osver/gcc/6.3.0/lib6:-I/source/zlib/1.2.8/include: -I/source/zlib/1.2.8/include -L/source/zlib/1.2.8/lib -I/source/bzip2/1.0.6/include -L/source/bzip2/1.0.6/lib -I/source/lzma/5.0.7/incl
ude -L/source/lzma/5.0.7/lib -I//apps/lib-osver/pcre/8.38/include -L/apps/lib-osver/pcre/8.38/lib -I/source/libcurl/7.35.0/include -I/source/libcurl/7.35.0/lib   -DNDEBUG src/data_set.c -o src
/data_set.o

gcc -c -I/apps/lib-osver/R/3.4.0/lib64/R/include -DNDEBUG   -I/apps/lib-osver/gcc/6.3.0//include -L/apps/lib-osver/gcc/6.3.0/lib64 -L/apps/lib-osver/gcc/6.3.0/lib6:-I/source/zlib/1.2.8/include
: -I/source/zlib/1.2.8/include -L/source/zlib/1.2.8/lib -I/source/bzip2/1.0.6/include -L/source/bzip2/1.0.6/lib -I/source/lzma/5.0.7/include -L/source/lzma/5.0.7/lib -I//apps/lib-osver/pcre/8.
38/include -L/apps/lib-osver/pcre/8.38/lib -I/source/libcurl/7.35.0/include -I/source/libcurl/7.35.0/lib    -fpic  -I/apps/lib-osver/gcc/6.3.0//include -L/apps/lib-osver/gcc/6.3.0/lib64 -L/app
s/lib-osver/gcc/6.3.0/lib6:-I/source/zlib/1.2.8/include: -I/source/zlib/1.2.8/include -L/source/zlib/1.2.8/lib -I/source/bzip2/1.0.6/include -L/source/bzip2/1.0.6/lib -I/source/lzma/5.0.7/incl
ude -L/source/lzma/5.0.7/lib -I//apps/lib-osver/pcre/8.38/include -L/apps/lib-osver/pcre/8.38/lib -I/source/libcurl/7.35.0/include -I/source/libcurl/7.35.0/lib   -DNDEBUG src/digraph_core.c -o
 src/digraph_core.o

src/digraph_core.c: In function ‘iscc_digraph_is_valid’:
src/digraph_core.c:62:2: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  for (size_t i = 0; i < dg->vertices; ++i) {
  ^
src/digraph_core.c:62:2: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
src/digraph_core.c:69:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
   for (const scc_PointIndex* arc = dg->head; arc != arc_stop; ++arc) {
   ^
make[1]: *** [src/digraph_core.o] Error 1
make[1]: Leaving directory `/tmp/RtmpsrwRMk/R.INSTALL21e47c3f3c6e/scclust/src/libscclust'
make: *** [libscclust/lib/libscclust.a] Error 1
ERROR: compilation failed for package ‘scclust’
</pre>
</details>

**Comment by fsavje** [comment]
This starts making sense. Thank you for your detective work! The sub-makefile should use the local Makeconf. I'll try to sort this out.

**Comment by fsavje** [comment]
@slowkow Version 0.2.1 should fix this problem. It should be on CRAN any moment now. Please let me know if it works for you.
