### ISSUE TITLE
Alernative input to distances objects in sc_clustering

### ISSUE THREAD

**Issue by ErvanCH** [fsavje/Rscclust#9]
Dear Frederik,
Thanks for the nice package. I noted that the base 'sc_clustering' function requires a 'distances' object. However, I am comparing lands based on environmental data and compute a multivariate ecological distance between each pairs of land. The output looks like this (fake example): 
data.frame(land1=c("A","A","A","B","B","B","C,","C","C"),land2=c("B","C","D","B","C","D","B","C","D",),ecodist=c(0.2,0.3,0.4,0.2,0.1,0.6,0.6,0.5,0.1)).
From that I can re-create a distance matrix where ecodist serves as distance. The format is essentially the same as a distances object, and could theoretically be passed into the sc_clustering function, isn't it?
Would be very usefull to have more flexilibility to pass alternative distance matrix format.
Many thanks!
Ervan

**Comment by fsavje** [comment]
Dear Ervan,

I'm glad you like the package.

What you want to do is possible, but it will require you to write a wrapper around the distance function you have in mind. In particular, what `distances` object from the [`distances` package](https://github.com/fsavje/distances) does is to expose a C API for its core functionality. This API is used by the scclust C library to call the `distances` object. Put differently, the normal R infrastructure provide way to call C from R. The API makes it possible to call R from C.

If you decide to write a wrapper, take a look at the [`distances` package](https://github.com/fsavje/distances). You only need to implement the functions that are part of the API specified in `inst/include/distancesAPI.h`.

Good luck!
